export const constants = {
  counting_game: {
    responses: [
      "Oops <USER>, looks like the numbers ran away from you! 🏃‍♂️ Let's chase them down again!",
      "Looks like you dropped a digit, <USER>. Try picking it up next time!",
      "Math may be hard, but we've got this <USER>. Let's do it again!",
      "Whoa <USER>! Those numbers are wilder than a herd of cats. Let's wrangle them up!",
      "Uh oh, <USER>... That count went on vacation. Try again!",
      "Your count needs more cowbell, <USER>! Give it another shot! 🔔",
      "Ah, you missed the mark, <USER>. Let's COUNT on you to try again!",
      "Numbers are hard, but not impossible, <USER>. You're one digit away from greatness!",
      "That wasn't your final COUNTdown, <USER>. Give it another go! 🎶",
      "Houston, we have a counting problem! <USER>, let's fix this math mission!",
      "Yikes, <USER>, that count is spookier than a ghost at Halloween! 🎃 Try again!",
      "Oopsie-doodle, <USER>, the count went off into another dimension! Let's bring it back!",
      "Looks like you tripped on a number there, <USER>. Let’s get back on track!",
      "One...two...wait, <USER>, that’s not it! Third time's the charm!",
      "Aww, numbers are being tricky today, huh? Try again, <USER>!",
      "Hmm... did we summon the wrong count spirit, <USER>? Let's try again! 👻",
      "That count slipped through your fingers, <USER>. Let’s grab it on the next try!",
      "Oh no, <USER>! The count’s lost in the matrix. Let’s reboot and try again!",
      "Seems like the numbers got scrambled, <USER>. Let’s unscramble them together!",
      "Close, but no banana! 🍌 Try it again, <USER>!",
      "Whoa, <USER>, that number went off the grid! Let’s reel it back in!",
      "Oops, <USER>, that count got tangled like headphone wires. Let’s untangle it!",
      "Looks like a wild number appeared, <USER>. Use logic! It’s super effective!",
      "Numbers can be tricky, but you're trickier, <USER>. Give it another shot!",
      "That count got away like socks in the laundry. Let’s find it again!",
      "Don’t worry <USER>, the numbers are just playing hard to count! Try again!",
      "Wait, <USER>, that wasn’t the right number! Did the calculator break? 🤖",
      "Oh no, <USER>! The numbers just threw a party without you. Let's join them!",
      "The numbers might be shy, <USER>. Let's coax them out together!",
      "Looks like the digits went rogue, <USER>. Time to rein them in!",
      "That count was close, <USER>... like a missed high five. Let's nail it next time!",
      "The count may be off, but your determination is on point, <USER>!",
      "Whoops, <USER>! The numbers decided to take a detour. Let's bring them back on track!",
      "Looks like we stumbled over a number, <USER>. Let's pick it up and keep counting!",
      "That count disappeared faster than a magician's trick! 🎩✨ Let's find it again, <USER>!",
      "Oh no, <USER>, the numbers went rogue! Time to bring them back in line!",
      "Looks like we need to recalibrate our counting compass, <USER>!",
      "Whoa, <USER>, the numbers got flipped upside down. Let's flip them back!",
      "That count slid off like butter on toast, <USER>. Let's stick it this time!",
      "Numbers playing hide and seek again, <USER>? Time to find them!",
      "Looks like the count went off into space, <USER>. Time to bring it back to Earth!",
    ],
  },
};
